### ISSUE TITLE
Question about Training

### ISSUE THREAD

**Issue by weiyang001** [daooshee/ReReVST-Code#5]
Hi,
Thank you so much for this project! Really a great work!
I am trying to test  this code (train.py) and having following error. Can you give me some help?
![error](https://user-images.githubusercontent.com/89854237/141681016-9a541695-792b-496a-a5ec-4a232ebb1836.png)

**Comment by daooshee** [comment]
I haven't met this problem before.
It says that the `style_img` is `None`. Maybe the training dataset is not complete (for example, there is a broken image)?
Or maybe you can use <`try:` read image `except:`  randomly load another image> to skip bad images.
Hope it helps~

**Comment by weiyang001** [comment]
Thanks for your quick reply！
I'll give this suggestion a try.  I just have two question that,

1. Is data cleaning necessary before using MSCOCO_train2014?
2. Could you share **".data/style/"** links you use? I guess there might be a problem with the style image dataset I was looking for.

Thanks！

**Comment by daooshee** [comment]
1. According to my experience, data cleaning is not necessary.
2. You can try [Painter by Numbers from Kaggle](https://www.kaggle.com/c/painter-by-numbers). The style image dataset actually can be any dataset of enough various painting images.

Hope this can help you :)

**Comment by weiyang001** [comment]
Although the new style dataset still had the same problems as the original, I was able to complete the training after using your suggestions.

Thank you for your answer!
